[package]
name = "loxidation"
version = "0.1.0"
authors = ["LevitatingBusinessMan <public@reinfernhout.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
